### ISSUE TITLE
error in Java grammar

### ISSUE THREAD

**Issue by anyahelene** [norswap/autumn#4]
```java
public enum Problem {
	A_IS_FOR_AARDVARKS, //
	B_IS_FOR_BANANAS, //
	C_IS_FOR_CEPHALOPDS, //
	D_IS_FOR_DOCTORS, //
	;

}
```

(See [JLS-8.9.1](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.9.1) and
	[JLS-14.20.3](https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.3))

**Comment by norswap** [comment]
fixed by 3871662978a8795ac0b4c017c0388841c823d6db
