### ISSUE TITLE
`ws()` throws NPE when `ws` isn't set

### ISSUE THREAD

**Issue by Kroppeb** [norswap/autumn#6]
`ws` says:
null by default, meaning no whitespace will be matched.

but the function `ws()` just tries to grab the parser, even if ws is null. I'd expect a null check and if it is indeed `null` return `empty` instead.

**Comment by norswap** [comment]
Excellent suggestion, and a quick fix too. I'll get around to that as soon as possible, otherwise feel free to submit a pull request.

**Comment by norswap** [comment]
Fixed by 8dfc763ce64f53f2ffa3a628572fcdbe30372526
